name: GitHub Contribution Snake

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate contribution snake graph
        uses: Platane/snk@v1.3.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          svg_out_path: github-contribution-grid-snake.svg
          colors: '["#444143", "#A19E9D", "#E2E2DA", "#DCE8E7", "#FFFFFF"]'
          background: '#444143'

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update snake contributions"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
